inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'app/frontend/**/*'
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "test/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "log/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 130
  Exclude:
    - "spec/**/*"
    - "config/**/*"

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/CommentIndentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/BlockNesting:
  Max: 5

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

